"""made time window field optional

Revision ID: 076820f4e84b
Revises: dfd73435294b
Create Date: 2025-03-04 15:02:49.040664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '076820f4e84b'
down_revision: Union[str, None] = 'dfd73435294b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forecastcoveragedownloadrequest', 'time_window',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forecastcoveragedownloadrequest', 'time_window',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
