"""added navigation-related columns

Revision ID: c9c28c2f26da
Revises: f6d4962c1f62
Create Date: 2025-03-10 15:14:10.547694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c9c28c2f26da'
down_revision: Union[str, None] = 'f6d4962c1f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecastcoverageconfiguration', sa.Column('include_in_advanced_section_combinations', sa.Boolean(), nullable=False))
    op.add_column('forecastcoverageconfiguration', sa.Column('include_in_simple_section_combinations', sa.Boolean(), nullable=False))
    op.add_column('historicalcoverageconfiguration', sa.Column('include_in_advanced_section_combinations', sa.Boolean(), nullable=False))
    op.add_column('historicalcoverageconfiguration', sa.Column('include_in_simple_section_combinations', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historicalcoverageconfiguration', 'include_in_simple_section_combinations')
    op.drop_column('historicalcoverageconfiguration', 'include_in_advanced_section_combinations')
    op.drop_column('forecastcoverageconfiguration', 'include_in_simple_section_combinations')
    op.drop_column('forecastcoverageconfiguration', 'include_in_advanced_section_combinations')
    # ### end Alembic commands ###
