"""added download request for time series

Revision ID: f6d4962c1f62
Revises: 076820f4e84b
Create Date: 2025-03-07 17:33:59.051535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6d4962c1f62'
down_revision: Union[str, None] = '076820f4e84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeseriesdownloadrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_datetime', sa.DateTime(), nullable=False),
    sa.Column('entity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_public_sector', sa.Boolean(), nullable=False),
    sa.Column('download_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('climatological_variable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aggregation_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('forecastcoveragedownloadrequest', 'request_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('historicalcoveragedownloadrequest', 'request_datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historicalcoveragedownloadrequest', 'request_datetime',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('forecastcoveragedownloadrequest', 'request_datetime',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_table('timeseriesdownloadrequest')
    # ### end Alembic commands ###
