"""added overview cov conf

Revision ID: 3cf64092202c
Revises: a39792a72d70
Create Date: 2025-02-04 14:30:08.487054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cf64092202c'
down_revision: Union[str, None] = 'a39792a72d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FORECAST', 'HISTORICAL', name='datacategory').create(op.get_bind())
    op.create_table('overviewcoverageconfiguration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netcdf_main_dataset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thredds_url_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('climatic_indicator_id', sa.Integer(), nullable=True),
    sa.Column('spatial_region_id', sa.Integer(), nullable=True),
    sa.Column('data_category', postgresql.ENUM('FORECAST', 'HISTORICAL', name='datacategory', create_type=False), nullable=False),
    sa.Column('lower_uncertainty_thredds_url_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lower_uncertainty_netcdf_main_dataset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upper_uncertainty_thredds_url_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upper_uncertainty_netcdf_main_dataset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scenarios', sa.ARRAY(postgresql.ENUM('RCP26', 'RCP45', 'RCP85', name='forecastscenario', create_type=False)), nullable=True),
    sa.ForeignKeyConstraint(['climatic_indicator_id'], ['climaticindicator.id'], ),
    sa.ForeignKeyConstraint(['spatial_region_id'], ['spatialregion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('historicalcoverageconfiguration', 'wms_main_layer_name')
    op.drop_column('historicalcoverageconfiguration', 'wms_secondary_layer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicalcoverageconfiguration', sa.Column('wms_secondary_layer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('historicalcoverageconfiguration', sa.Column('wms_main_layer_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('overviewcoverageconfiguration')
    sa.Enum('FORECAST', 'HISTORICAL', name='datacategory').drop(op.get_bind())
    # ### end Alembic commands ###
