"""made time window name unique

Revision ID: 4216aa97cdd8
Revises: 132a6f461620
Create Date: 2025-01-17 18:42:07.532761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4216aa97cdd8'
down_revision: Union[str, None] = '132a6f461620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'forecasttimewindow', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forecasttimewindow', type_='unique')
    # ### end Alembic commands ###
