"""remove indicator internal name

Revision ID: 423274dc64be
Revises: 41c6050a217c
Create Date: 2025-01-09 17:00:42.760152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '423274dc64be'
down_revision: Union[str, None] = '41c6050a217c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observationseriesconfiguration', 'indicator_internal_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observationseriesconfiguration', sa.Column('indicator_internal_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
