"""added clim indicator forecast model base path

Revision ID: 49c63e7f2c08
Revises: 6a75abad3e5a
Create Date: 2025-01-13 18:50:09.218458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '49c63e7f2c08'
down_revision: Union[str, None] = '6a75abad3e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecastmodelclimaticindicatorlink',
    sa.Column('forecast_model_id', sa.Integer(), nullable=False),
    sa.Column('climatic_indicator_id', sa.Integer(), nullable=False),
    sa.Column('thredds_url_base_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['climatic_indicator_id'], ['climaticindicator.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['forecast_model_id'], ['forecastmodel.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_model_id', 'climatic_indicator_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecastmodelclimaticindicatorlink')
    # ### end Alembic commands ###
