"""removed relationship between variable and measurements

Revision ID: 4b4e00bb8c66
Revises: ca42ab8be733
Create Date: 2024-11-08 16:01:09.317458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b4e00bb8c66'
down_revision: Union[str, None] = 'ca42ab8be733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('monthlymeasurement_variable_id_fkey', 'monthlymeasurement', type_='foreignkey')
    op.drop_column('monthlymeasurement', 'variable_id')
    op.drop_constraint('seasonalmeasurement_variable_id_fkey', 'seasonalmeasurement', type_='foreignkey')
    op.drop_column('seasonalmeasurement', 'variable_id')
    op.drop_constraint('yearlymeasurement_variable_id_fkey', 'yearlymeasurement', type_='foreignkey')
    op.drop_column('yearlymeasurement', 'variable_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yearlymeasurement', sa.Column('variable_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('yearlymeasurement_variable_id_fkey', 'yearlymeasurement', 'variable', ['variable_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('seasonalmeasurement', sa.Column('variable_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('seasonalmeasurement_variable_id_fkey', 'seasonalmeasurement', 'variable', ['variable_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('monthlymeasurement', sa.Column('variable_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('monthlymeasurement_variable_id_fkey', 'monthlymeasurement', 'variable', ['variable_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
