"""made spatial region name unique

Revision ID: 5dec4a8e29cb
Revises: 942aecd297b4
Create Date: 2025-01-17 15:35:42.960001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5dec4a8e29cb'
down_revision: Union[str, None] = '942aecd297b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'spatialregion', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spatialregion', type_='unique')
    # ### end Alembic commands ###
