"""added relationship between climaticindicator and coverageconfiguration

Revision ID: 630cc1e4556d
Revises: ce2f4800cc76
Create Date: 2024-10-29 16:11:06.851157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '630cc1e4556d'
down_revision: Union[str, None] = 'ce2f4800cc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverageconfiguration', sa.Column('climatic_indicator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coverageconfiguration', 'climaticindicator', ['climatic_indicator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coverageconfiguration', type_='foreignkey')
    op.drop_column('coverageconfiguration', 'climatic_indicator_id')
    # ### end Alembic commands ###
