"""added link betweem forecast cov conf and model

Revision ID: 66aab565d68b
Revises: 49c63e7f2c08
Create Date: 2025-01-14 16:33:55.184287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66aab565d68b'
down_revision: Union[str, None] = '49c63e7f2c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecastcoverageconfigurationforecastmodellink',
    sa.Column('forecast_coverage_configuration_id', sa.Integer(), nullable=False),
    sa.Column('forecast_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_coverage_configuration_id'], ['forecastcoverageconfiguration.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['forecast_model_id'], ['forecastmodel.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('forecast_coverage_configuration_id', 'forecast_model_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecastcoverageconfigurationforecastmodellink')
    # ### end Alembic commands ###
