"""removed forecast model internal value

Revision ID: 6a75abad3e5a
Revises: 418fe19133c0
Create Date: 2025-01-13 18:31:54.943292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a75abad3e5a'
down_revision: Union[str, None] = '418fe19133c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecastmodel', 'coverage_base_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecastmodel', sa.Column('coverage_base_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
