"""added overviews

Revision ID: 7067c8da7c49
Revises: a39792a72d70
Create Date: 2025-02-05 13:12:11.283067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7067c8da7c49'
down_revision: Union[str, None] = 'a39792a72d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecastoverviewseriesconfiguration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netcdf_main_dataset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thredds_url_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('climatic_indicator_id', sa.Integer(), nullable=True),
    sa.Column('lower_uncertainty_thredds_url_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lower_uncertainty_netcdf_main_dataset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upper_uncertainty_thredds_url_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upper_uncertainty_netcdf_main_dataset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scenarios', sa.ARRAY(postgresql.ENUM('RCP26', 'RCP45', 'RCP85', name='forecastscenario', create_type=False)), nullable=True),
    sa.ForeignKeyConstraint(['climatic_indicator_id'], ['climaticindicator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observationoverviewseriesconfiguration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netcdf_main_dataset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thredds_url_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('climatic_indicator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['climatic_indicator_id'], ['climaticindicator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('historicalcoverageconfiguration', 'wms_secondary_layer_name')
    op.drop_column('historicalcoverageconfiguration', 'wms_main_layer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicalcoverageconfiguration', sa.Column('wms_main_layer_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('historicalcoverageconfiguration', sa.Column('wms_secondary_layer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('observationoverviewseriesconfiguration')
    op.drop_table('forecastoverviewseriesconfiguration')
    # ### end Alembic commands ###
