"""added relationship between measurement and climatic_indicator

Revision ID: 7b7412888496
Revises: e20d856daca4
Create Date: 2024-11-14 17:00:26.871034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b7412888496'
down_revision: Union[str, None] = 'e20d856daca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlymeasurement', sa.Column('climatic_indicator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'monthlymeasurement', 'climaticindicator', ['climatic_indicator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('seasonalmeasurement', sa.Column('climatic_indicator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'seasonalmeasurement', 'climaticindicator', ['climatic_indicator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('yearlymeasurement', sa.Column('climatic_indicator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'yearlymeasurement', 'climaticindicator', ['climatic_indicator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yearlymeasurement', type_='foreignkey')
    op.drop_column('yearlymeasurement', 'climatic_indicator_id')
    op.drop_constraint(None, 'seasonalmeasurement', type_='foreignkey')
    op.drop_column('seasonalmeasurement', 'climatic_indicator_id')
    op.drop_constraint(None, 'monthlymeasurement', type_='foreignkey')
    op.drop_column('monthlymeasurement', 'climatic_indicator_id')
    # ### end Alembic commands ###
