"""added missing year periods in groups table

Revision ID: 8ac81e2116a5
Revises: c85d74f18e7b
Create Date: 2025-02-15 21:04:46.089185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ac81e2116a5'
down_revision: Union[str, None] = 'c85d74f18e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ALL_YEAR', 'WINTER', 'SPRING', 'SUMMER', 'AUTUMN', 'JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', name='historicalyearperiod').create(op.get_bind())
    sa.Enum('ALL_YEAR', 'WINTER', 'SPRING', 'SUMMER', 'AUTUMN', name='forecastyearperiod').create(op.get_bind())
    op.add_column('forecastyearperiodgroup', sa.Column('year_periods', sa.ARRAY(postgresql.ENUM('ALL_YEAR', 'WINTER', 'SPRING', 'SUMMER', 'AUTUMN', name='forecastyearperiod', create_type=False)), nullable=True))
    op.add_column('historicalyearperiodgroup', sa.Column('year_periods', sa.ARRAY(postgresql.ENUM('ALL_YEAR', 'WINTER', 'SPRING', 'SUMMER', 'AUTUMN', 'JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', name='historicalyearperiod', create_type=False)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historicalyearperiodgroup', 'year_periods')
    op.drop_column('forecastyearperiodgroup', 'year_periods')
    sa.Enum('ALL_YEAR', 'WINTER', 'SPRING', 'SUMMER', 'AUTUMN', name='forecastyearperiod').drop(op.get_bind())
    sa.Enum('ALL_YEAR', 'WINTER', 'SPRING', 'SUMMER', 'AUTUMN', 'JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', name='historicalyearperiod').drop(op.get_bind())
    # ### end Alembic commands ###
