"""changed names of station owners

Revision ID: 8df4e65677d9
Revises: 9c278ecdeb38
Create Date: 2024-12-13 14:34:06.423950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '8df4e65677d9'
down_revision: Union[str, None] = '9c278ecdeb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'observationstationowner', ['ARPAV', 'ARPAFVG'],
                        [TableReference(table_schema='public', table_name='observationstation', column_name='owner')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'observationstationowner', ['ARPA_V', 'ARPA_FVG'],
                        [TableReference(table_schema='public', table_name='observationstation', column_name='owner')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
