"""added spatial region internal value

Revision ID: a410aa66a691
Revises: cbcd3d0ffc55
Create Date: 2025-01-29 16:08:01.842392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a410aa66a691'
down_revision: Union[str, None] = 'cbcd3d0ffc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spatialregion', sa.Column('internal_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spatialregion', 'internal_value')
    # ### end Alembic commands ###
