"""forecast and year groups are now 1_n

Revision ID: c85d74f18e7b
Revises: 6dbeb73f6b5d
Create Date: 2025-02-15 20:13:31.791103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c85d74f18e7b'
down_revision: Union[str, None] = '6dbeb73f6b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecastcoverageconfiguration', sa.Column('forecast_model_group_id', sa.Integer(), nullable=True))
    op.add_column('forecastcoverageconfiguration', sa.Column('year_period_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forecastcoverageconfiguration', 'forecastmodelgroup', ['forecast_model_group_id'], ['id'])
    op.create_foreign_key(None, 'forecastcoverageconfiguration', 'forecastyearperiodgroup', ['year_period_group_id'], ['id'])
    op.add_column('historicalcoverageconfiguration', sa.Column('year_period_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'historicalcoverageconfiguration', 'historicalyearperiodgroup', ['year_period_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historicalcoverageconfiguration', type_='foreignkey')
    op.drop_column('historicalcoverageconfiguration', 'year_period_group_id')
    op.drop_constraint(None, 'forecastcoverageconfiguration', type_='foreignkey')
    op.drop_constraint(None, 'forecastcoverageconfiguration', type_='foreignkey')
    op.drop_column('forecastcoverageconfiguration', 'year_period_group_id')
    op.drop_column('forecastcoverageconfiguration', 'forecast_model_group_id')
    # ### end Alembic commands ###
