"""explicitly relate station and indicator

Revision ID: cbcd3d0ffc55
Revises: f8f29f273ebf
Create Date: 2025-01-23 11:44:04.540590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbcd3d0ffc55'
down_revision: Union[str, None] = 'f8f29f273ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observationstationclimaticindicatorlink',
    sa.Column('observation_station_id', sa.Integer(), nullable=False),
    sa.Column('climatic_indicator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['climatic_indicator_id'], ['climaticindicator.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_station_id'], ['observationstation.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observation_station_id', 'climatic_indicator_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observationstationclimaticindicatorlink')
    # ### end Alembic commands ###
