"""added climaticindicator table

Revision ID: ce2f4800cc76
Revises: 4df282a0319d
Create Date: 2024-10-29 13:30:29.859589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce2f4800cc76'
down_revision: Union[str, None] = '4df282a0319d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ANNUAL', 'THIRTY_YEAR', name='aggregationperiod').create(op.get_bind())
    sa.Enum('ABSOLUTE', 'ANOMALY', name='measuretype').create(op.get_bind())
    op.create_table('climaticindicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('measure_type', postgresql.ENUM('ABSOLUTE', 'ANOMALY', name='measuretype', create_type=False), nullable=False),
    sa.Column('aggregation_period', postgresql.ENUM('ANNUAL', 'THIRTY_YEAR', name='aggregationperiod', create_type=False), nullable=False),
    sa.Column('display_name_english', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_english', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_english', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_italian', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('palette', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color_scale_min', sa.Float(), nullable=False),
    sa.Column('color_scale_max', sa.Float(), nullable=False),
    sa.Column('data_precision', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('climaticindicator')
    sa.Enum('ABSOLUTE', 'ANOMALY', name='measuretype').drop(op.get_bind())
    sa.Enum('ANNUAL', 'THIRTY_YEAR', name='aggregationperiod').drop(op.get_bind())
    # ### end Alembic commands ###
