"""added model-dependent uncertainties base path

Revision ID: f2e5cc37ed4c
Revises: 66aab565d68b
Create Date: 2025-01-15 15:40:23.222705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2e5cc37ed4c'
down_revision: Union[str, None] = '66aab565d68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecastmodelclimaticindicatorlink', sa.Column('thredds_url_uncertainties_base_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecastmodelclimaticindicatorlink', 'thredds_url_uncertainties_base_path')
    # ### end Alembic commands ###
