"""use enum for station managers

Revision ID: f8f29f273ebf
Revises: 4216aa97cdd8
Create Date: 2025-01-20 16:49:21.956768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8f29f273ebf'
down_revision: Union[str, None] = '4216aa97cdd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'observationseriesconfiguration',
        'station_managers',
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        postgresql_using='station_managers::observationstationmanager[]',
        type_=sa.ARRAY(
            sa.Enum('ARPAV', 'ARPAFVG', name='observationstationmanager')
        ),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observationseriesconfiguration', 'station_managers',
               existing_type=sa.ARRAY(sa.Enum('ARPAV', 'ARPAFVG', name='observationstationmanager')),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
