"""removed relationship between variable and coverage configuration

Revision ID: fdbc5e0bfb13
Revises: 4b4e00bb8c66
Create Date: 2024-11-08 18:27:36.014054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdbc5e0bfb13'
down_revision: Union[str, None] = '4b4e00bb8c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coverageconfiguration_observation_variable_id_fkey', 'coverageconfiguration', type_='foreignkey')
    op.drop_column('coverageconfiguration', 'observation_variable_id')
    op.drop_column('coverageconfiguration', 'observation_variable_aggregation_type')
    sa.Enum('MONTHLY', 'SEASONAL', 'YEARLY', name='observationaggregationtype').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MONTHLY', 'SEASONAL', 'YEARLY', name='observationaggregationtype').create(op.get_bind())
    op.add_column('coverageconfiguration', sa.Column('observation_variable_aggregation_type', postgresql.ENUM('MONTHLY', 'SEASONAL', 'YEARLY', name='observationaggregationtype', create_type=False), autoincrement=False, nullable=True))
    op.add_column('coverageconfiguration', sa.Column('observation_variable_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('coverageconfiguration_observation_variable_id_fkey', 'coverageconfiguration', 'variable', ['observation_variable_id'], ['id'])
    # ### end Alembic commands ###
